//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSData.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("some vale")]
        public string test {
            get {
                return ((string)(this["test"]));
            }
            set {
                this["test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string SEQ_NO {
            get {
                return ((string)(this["SEQ_NO"]));
            }
            set {
                this["SEQ_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("461")]
        public string BIT_ID {
            get {
                return ((string)(this["BIT_ID"]));
            }
            set {
                this["BIT_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25489")]
        public string MOBILE_NO {
            get {
                return ((string)(this["MOBILE_NO"]));
            }
            set {
                this["MOBILE_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("산뒤마을")]
        public string STATION_NM {
            get {
                return ((string)(this["STATION_NM"]));
            }
            set {
                this["STATION_NM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.255.164")]
        public string SERVER_URL {
            get {
                return ((string)(this["SERVER_URL"]));
            }
            set {
                this["SERVER_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SERVER_TYPE {
            get {
                return ((string)(this["SERVER_TYPE"]));
            }
            set {
                this["SERVER_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9001")]
        public string SERVER_PORT {
            get {
                return ((string)(this["SERVER_PORT"]));
            }
            set {
                this["SERVER_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string FTP_GBN {
            get {
                return ((string)(this["FTP_GBN"]));
            }
            set {
                this["FTP_GBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTP_IP {
            get {
                return ((string)(this["FTP_IP"]));
            }
            set {
                this["FTP_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string FTP_PORT {
            get {
                return ((string)(this["FTP_PORT"]));
            }
            set {
                this["FTP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTP_USERID {
            get {
                return ((string)(this["FTP_USERID"]));
            }
            set {
                this["FTP_USERID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTP_USERPWD {
            get {
                return ((string)(this["FTP_USERPWD"]));
            }
            set {
                this["FTP_USERPWD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.255.165")]
        public string HTTP_URL {
            get {
                return ((string)(this["HTTP_URL"]));
            }
            set {
                this["HTTP_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8080")]
        public string HTTP_PORT {
            get {
                return ((string)(this["HTTP_PORT"]));
            }
            set {
                this["HTTP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ENV_GBN {
            get {
                return ((string)(this["ENV_GBN"]));
            }
            set {
                this["ENV_GBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ENV_PORT_NM {
            get {
                return ((string)(this["ENV_PORT_NM"]));
            }
            set {
                this["ENV_PORT_NM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57600")]
        public string ENV_BAUD_RATE {
            get {
                return ((string)(this["ENV_BAUD_RATE"]));
            }
            set {
                this["ENV_BAUD_RATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string CAM_NO1 {
            get {
                return ((string)(this["CAM_NO1"]));
            }
            set {
                this["CAM_NO1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string CAM_NO1_ROTATE {
            get {
                return ((string)(this["CAM_NO1_ROTATE"]));
            }
            set {
                this["CAM_NO1_ROTATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string CAM_NO2 {
            get {
                return ((string)(this["CAM_NO2"]));
            }
            set {
                this["CAM_NO2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string CAM_NO2_ROTATE {
            get {
                return ((string)(this["CAM_NO2_ROTATE"]));
            }
            set {
                this["CAM_NO2_ROTATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string LOGSAVE_DAY {
            get {
                return ((string)(this["LOGSAVE_DAY"]));
            }
            set {
                this["LOGSAVE_DAY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string LOGSAVE_PERCENT {
            get {
                return ((string)(this["LOGSAVE_PERCENT"]));
            }
            set {
                this["LOGSAVE_PERCENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string ENV_USE_FAN_MANUAL {
            get {
                return ((string)(this["ENV_USE_FAN_MANUAL"]));
            }
            set {
                this["ENV_USE_FAN_MANUAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string ENV_USE_HEATER_MANUAL {
            get {
                return ((string)(this["ENV_USE_HEATER_MANUAL"]));
            }
            set {
                this["ENV_USE_HEATER_MANUAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string SHOCK_DETECT_NO {
            get {
                return ((string)(this["SHOCK_DETECT_NO"]));
            }
            set {
                this["SHOCK_DETECT_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public string Volume {
            get {
                return ((string)(this["Volume"]));
            }
            set {
                this["Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string ArriveSoonGBN {
            get {
                return ((string)(this["ArriveSoonGBN"]));
            }
            set {
                this["ArriveSoonGBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public string ArriveSoonTimeGBN {
            get {
                return ((string)(this["ArriveSoonTimeGBN"]));
            }
            set {
                this["ArriveSoonTimeGBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string ArriveSoonStationGBN {
            get {
                return ((string)(this["ArriveSoonStationGBN"]));
            }
            set {
                this["ArriveSoonStationGBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0430")]
        public string MonitorOnTime {
            get {
                return ((string)(this["MonitorOnTime"]));
            }
            set {
                this["MonitorOnTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0100")]
        public string MonitorOffTime {
            get {
                return ((string)(this["MonitorOffTime"]));
            }
            set {
                this["MonitorOffTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DefaultLCDLux {
            get {
                return ((string)(this["DefaultLCDLux"]));
            }
            set {
                this["DefaultLCDLux"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string LuxCount {
            get {
                return ((string)(this["LuxCount"]));
            }
            set {
                this["LuxCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string BITOrderGBN {
            get {
                return ((string)(this["BITOrderGBN"]));
            }
            set {
                this["BITOrderGBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string UseDetectSensor {
            get {
                return ((string)(this["UseDetectSensor"]));
            }
            set {
                this["UseDetectSensor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string DetectSensorServiceTime {
            get {
                return ((string)(this["DetectSensorServiceTime"]));
            }
            set {
                this["DetectSensorServiceTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string FANMaxTemp {
            get {
                return ((string)(this["FANMaxTemp"]));
            }
            set {
                this["FANMaxTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string FANMinTemp {
            get {
                return ((string)(this["FANMinTemp"]));
            }
            set {
                this["FANMinTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string HeaterMaxTemp {
            get {
                return ((string)(this["HeaterMaxTemp"]));
            }
            set {
                this["HeaterMaxTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string HeaterMinTemp {
            get {
                return ((string)(this["HeaterMinTemp"]));
            }
            set {
                this["HeaterMinTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string ShockDetectValue {
            get {
                return ((string)(this["ShockDetectValue"]));
            }
            set {
                this["ShockDetectValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string BITFontSize {
            get {
                return ((string)(this["BITFontSize"]));
            }
            set {
                this["BITFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TestOperationDisplayYN {
            get {
                return ((string)(this["TestOperationDisplayYN"]));
            }
            set {
                this["TestOperationDisplayYN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Reserve1 {
            get {
                return ((string)(this["Reserve1"]));
            }
            set {
                this["Reserve1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string PromotionRefreshInterval {
            get {
                return ((string)(this["PromotionRefreshInterval"]));
            }
            set {
                this["PromotionRefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string BusArrivalReshreshInterval {
            get {
                return ((string)(this["BusArrivalReshreshInterval"]));
            }
            set {
                this["BusArrivalReshreshInterval"] = value;
            }
        }
    }
}
