//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSData {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SEQ_NO {
            get {
                return ((int)(this["SEQ_NO"]));
            }
            set {
                this["SEQ_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("461")]
        public int BIT_ID {
            get {
                return ((int)(this["BIT_ID"]));
            }
            set {
                this["BIT_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25489")]
        public int MOBILE_NO {
            get {
                return ((int)(this["MOBILE_NO"]));
            }
            set {
                this["MOBILE_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\uC0B0\\uB4A4\\uB9C8\\uC744")]
        public string STATION_NM {
            get {
                return ((string)(this["STATION_NM"]));
            }
            set {
                this["STATION_NM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.255.164")]
        public string SERVER_URL {
            get {
                return ((string)(this["SERVER_URL"]));
            }
            set {
                this["SERVER_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SERVER_TYPE {
            get {
                return ((int)(this["SERVER_TYPE"]));
            }
            set {
                this["SERVER_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9001")]
        public string SERVER_PORT {
            get {
                return ((string)(this["SERVER_PORT"]));
            }
            set {
                this["SERVER_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FTP_GBN {
            get {
                return ((int)(this["FTP_GBN"]));
            }
            set {
                this["FTP_GBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTP_IP {
            get {
                return ((string)(this["FTP_IP"]));
            }
            set {
                this["FTP_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FTP_PORT {
            get {
                return ((int)(this["FTP_PORT"]));
            }
            set {
                this["FTP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTP_USERID {
            get {
                return ((string)(this["FTP_USERID"]));
            }
            set {
                this["FTP_USERID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTP_USERPWD {
            get {
                return ((string)(this["FTP_USERPWD"]));
            }
            set {
                this["FTP_USERPWD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.255.165")]
        public string HTTP_URL {
            get {
                return ((string)(this["HTTP_URL"]));
            }
            set {
                this["HTTP_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8080")]
        public int HTTP_PORT {
            get {
                return ((int)(this["HTTP_PORT"]));
            }
            set {
                this["HTTP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ENV_GBN {
            get {
                return ((int)(this["ENV_GBN"]));
            }
            set {
                this["ENV_GBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ENV_PORT_NM {
            get {
                return ((string)(this["ENV_PORT_NM"]));
            }
            set {
                this["ENV_PORT_NM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57600")]
        public int ENV_BAUD_RATE {
            get {
                return ((int)(this["ENV_BAUD_RATE"]));
            }
            set {
                this["ENV_BAUD_RATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAM_NO1 {
            get {
                return ((int)(this["CAM_NO1"]));
            }
            set {
                this["CAM_NO1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAM_NO1_ROTATE {
            get {
                return ((int)(this["CAM_NO1_ROTATE"]));
            }
            set {
                this["CAM_NO1_ROTATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAM_NO2 {
            get {
                return ((int)(this["CAM_NO2"]));
            }
            set {
                this["CAM_NO2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAM_NO2_ROTATE {
            get {
                return ((int)(this["CAM_NO2_ROTATE"]));
            }
            set {
                this["CAM_NO2_ROTATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2024-08-26T13:50:32.1690974")]
        public string REGDATE {
            get {
                return ((string)(this["REGDATE"]));
            }
            set {
                this["REGDATE"] = value;
            }
        }
    }
}
